[profile.default]
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'
allow_paths = ["../node_modules"]
solc = '0.8.17'
optimizer = true
optimizer_runs = 999_999
fs_permissions = [{ access = "read", path = "./environment/"}]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain=11155111 }
polygon = { key = "${POLYGONSCAN_API_KEY}", chain=137, url="https://api.polygonscan.com/" }
mumbai = { key = "${POLYGONSCAN_API_KEY}", chain=80001, url="https://api-testnet.polygonscan.com/" }
